language: generic
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      env: PERFORM_MAKE_TEST=1
    - os: osx
      osx_image: xcode8.2
      env: SWIFT_VERSION=3.0.2 PERFORM_MAKE_TEST=1
    - os: osx
      osx_image: xcode8.2
      env: SWIFT_VERSION=3.1-DEVELOPMENT-SNAPSHOT-2017-03-06-a PERFORM_MAKE_TEST=1
addons:
  mariadb: '10.1'
env:
  global:
    #- SWIFT_VERSION=3.0.2
    #- TOOLCHAINS=org.swift.3020160919a
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mariadb; fi
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql.server start; fi
  - mysql -u root -e "create database IF NOT EXISTS test;"
script:
  - make debug
  - make release
  - if [[ "$PERFORM_MAKE_TEST" == "1" ]]; then make test; fi
  