language: generic
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env: SWIFT_VERSION=4.0.3
    - os: linux
      env: SWIFT_VERSION=4.1
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3
env:
  global:
    - PERFORM_MAKE_TEST=1
services: mysql
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap vapor/homebrew-tap && brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmysql; fi
install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)" ; fi
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql.server start; fi
  - mysql -u root -e "create database IF NOT EXISTS test;"
script:
  - swift build
  - if [[ "$PERFORM_MAKE_TEST" == "1" ]]; then swift test; fi
